version: '3.8'

services:
  web:
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - redis
    
      

  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    
