version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "5002:5002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - redis

  web:
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    build: .


    depends_on:
      - redis
    
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    
